import { Question } from '@/types';

export interface QuestionPreset {
  id: string;
  name: string;
  category: string;
  description: string;
  questions: Array<Omit<Question, 'id' | 'room_id'>>;
}

export const QUESTION_PRESETS: QuestionPreset[] = [
  {
    id: 'sains-logika',
    name: 'Tantangan Sains & Logika Cepat',
    category: 'Sains & Umum',
    description: '8 soal seputar sains, astronomi, biologi, dan penalaran cepat.',
    questions: [
      {
        question_text: 'Planet apakah di tata surya kita yang dijuluki sebagai "Planet Merah"?',
        options: [
          { label: 'A', text: 'Venus' },
          { label: 'B', text: 'Mars' },
          { label: 'C', text: 'Jupiter' },
          { label: 'D', text: 'Merkurius' },
        ],
        correct_answer: 'B',
        points: 100,
        order_index: 1,
        explanation: 'Mars tampak kemerahan karena permukaannya kaya akan besi oksida (karat).',
      },
      {
        question_text: 'Berapakah hasil dari operasi hitung: 12 + 8 * 4 - 10?',
        options: [
          { label: 'A', text: '34' },
          { label: 'B', text: '70' },
          { label: 'C', text: '42' },
          { label: 'D', text: '54' },
        ],
        correct_answer: 'A',
        points: 100,
        order_index: 2,
        explanation: 'Dahulukan perkalian: 8 * 4 = 32. Kemudian 12 + 32 - 10 = 34.',
      },
      {
        question_text: 'Organ tubuh manusia yang berfungsi memompa darah ke seluruh tubuh adalah...',
        options: [
          { label: 'A', text: 'Paru-paru' },
          { label: 'B', text: 'Hati' },
          { label: 'C', text: 'Jantung' },
          { label: 'D', text: 'Ginjal' },
        ],
        correct_answer: 'C',
        points: 100,
        order_index: 3,
        explanation: 'Jantung adalah otot berongga yang bertindak memompa darah ke sistem peredaran.',
      },
      {
        question_text: 'Jika sebuah mobil melaju 90 km/jam selama 40 menit, berapa kilometer jarak yang ditempuh?',
        options: [
          { label: 'A', text: '50 km' },
          { label: 'B', text: '60 km' },
          { label: 'C', text: '70 km' },
          { label: 'D', text: '45 km' },
        ],
        correct_answer: 'B',
        points: 200,
        order_index: 4,
        explanation: '40 menit = 40/60 jam = 2/3 jam. Jarak = 90 km/jam * 2/3 jam = 60 km.',
      },
      {
        question_text: 'Gas apakah yang paling melimpah di atmosfer bumi (mencapai sekitar 78%)?',
        options: [
          { label: 'A', text: 'Oksigen' },
          { label: 'B', text: 'Karbon Dioksida' },
          { label: 'C', text: 'Nitrogen' },
          { label: 'D', text: 'Argon' },
        ],
        correct_answer: 'C',
        points: 200,
        order_index: 5,
        explanation: 'Nitrogen (N2) menyusun sekitar 78% volume udara di atmosfer bumi.',
      },
      {
        question_text: 'Siapakah ilmuwan yang menemukan hukum gravitasi universal setelah terinspirasi melihat apel jatuh?',
        options: [
          { label: 'A', text: 'Albert Einstein' },
          { label: 'B', text: 'Nikola Tesla' },
          { label: 'C', text: 'Galileo Galilei' },
          { label: 'D', text: 'Sir Isaac Newton' },
        ],
        correct_answer: 'D',
        points: 200,
        order_index: 6,
        explanation: 'Sir Isaac Newton merumuskan hukum gravitasi universal pada tahun 1687.',
      },
      {
        question_text: 'Sebuah pola angka: 2, 6, 12, 20, 30, ... Angka berikutnya dalam deret ini adalah?',
        options: [
          { label: 'A', text: '40' },
          { label: 'B', text: '42' },
          { label: 'C', text: '44' },
          { label: 'D', text: '46' },
        ],
        correct_answer: 'B',
        points: 300,
        order_index: 7,
        explanation: 'Selisih antar suku: +4, +6, +8, +10, berikutnya +12. Jadi 30 + 12 = 42.',
      },
      {
        question_text: 'Bagian sel tumbuhan yang bertanggung jawab dalam proses fotosintesis dan memberi pigmen hijau adalah...',
        options: [
          { label: 'A', text: 'Mitokondria' },
          { label: 'B', text: 'Kloroplas' },
          { label: 'C', text: 'Ribosom' },
          { label: 'D', text: 'Vakuola' },
        ],
        correct_answer: 'B',
        points: 300,
        order_index: 8,
        explanation: 'Kloroplas mengandung klorofil yang menyerap energi cahaya matahari untuk fotosintesis.',
      },
    ],
  },
  {
    id: 'matematika-kilat',
    name: 'Matematika & Aritmatika Kilat',
    category: 'Matematika',
    description: '8 soal seru seputar aljabar dasar, persentase diskon, rasio, dan geometri.',
    questions: [
      {
        question_text: 'Sebuah baju seharga Rp 150.000 mendapat diskon 20%. Berapakah harga baju tersebut setelah diskon?',
        options: [
          { label: 'A', text: 'Rp 110.000' },
          { label: 'B', text: 'Rp 120.000' },
          { label: 'C', text: 'Rp 125.000' },
          { label: 'D', text: 'Rp 130.000' },
        ],
        correct_answer: 'B',
        points: 100,
        order_index: 1,
        explanation: 'Diskon 20% = 0.2 * 150.000 = Rp 30.000. Harga bayar = 150.000 - 30.000 = Rp 120.000.',
      },
      {
        question_text: 'Berapakah nilai x dari persamaan: 3x - 7 = 14?',
        options: [
          { label: 'A', text: '5' },
          { label: 'B', text: '6' },
          { label: 'C', text: '7' },
          { label: 'D', text: '8' },
        ],
        correct_answer: 'C',
        points: 100,
        order_index: 2,
        explanation: '3x = 14 + 7 = 21 -> x = 21 / 3 = 7.',
      },
      {
        question_text: 'Sebuah persegi panjang memiliki panjang 14 cm dan lebar 6 cm. Berapakah kelilingnya?',
        options: [
          { label: 'A', text: '40 cm' },
          { label: 'B', text: '84 cm' },
          { label: 'C', text: '20 cm' },
          { label: 'D', text: '48 cm' },
        ],
        correct_answer: 'A',
        points: 100,
        order_index: 3,
        explanation: 'Keliling = 2 * (panjang + lebar) = 2 * (14 + 6) = 2 * 20 = 40 cm.',
      },
      {
        question_text: 'Rasio kelereng Andi dan Budi adalah 3 : 5. Jika total kelereng mereka ada 40 butir, berapa butir kelereng milik Budi?',
        options: [
          { label: 'A', text: '15 butir' },
          { label: 'B', text: '20 butir' },
          { label: 'C', text: '25 butir' },
          { label: 'D', text: '30 butir' },
        ],
        correct_answer: 'C',
        points: 200,
        order_index: 4,
        explanation: 'Budi = 5 / (3 + 5) * 40 = 5/8 * 40 = 25 butir.',
      },
      {
        question_text: 'Berapakah akar pangkat tiga dari 1.728?',
        options: [
          { label: 'A', text: '11' },
          { label: 'B', text: '12' },
          { label: 'C', text: '13' },
          { label: 'D', text: '14' },
        ],
        correct_answer: 'B',
        points: 200,
        order_index: 5,
        explanation: '12 * 12 * 12 = 144 * 12 = 1.728.',
      },
      {
        question_text: 'Rata-rata nilai 4 ulangan matematika Rian adalah 80. Jika pada ulangan ke-5 ia mendapat 95, berapakah rata-rata barunya?',
        options: [
          { label: 'A', text: '82' },
          { label: 'B', text: '83' },
          { label: 'C', text: '84' },
          { label: 'D', text: '85' },
        ],
        correct_answer: 'B',
        points: 200,
        order_index: 6,
        explanation: 'Total nilai awal = 4 * 80 = 320. Total baru = 320 + 95 = 415. Rata-rata = 415 / 5 = 83.',
      },
      {
        question_text: 'Sebuah segitiga siku-siku memiliki alas 9 cm dan tinggi 12 cm. Berapakah panjang sisi miring (hipotenusa) segitiga tersebut?',
        options: [
          { label: 'A', text: '14 cm' },
          { label: 'B', text: '15 cm' },
          { label: 'C', text: '16 cm' },
          { label: 'D', text: '18 cm' },
        ],
        correct_answer: 'B',
        points: 300,
        order_index: 7,
        explanation: 'Teorema Pythagoras: c = akar(9^2 + 12^2) = akar(81 + 144) = akar(225) = 15 cm.',
      },
      {
        question_text: 'Jika 6 orang pekerja dapat menyelesaikan sebuah pekerjaan dalam 8 hari, berapa harikah pekerjaan tersebut selesai jika dikerjakan oleh 4 orang pekerja?',
        options: [
          { label: 'A', text: '10 hari' },
          { label: 'B', text: '12 hari' },
          { label: 'C', text: '14 hari' },
          { label: 'D', text: '16 hari' },
        ],
        correct_answer: 'B',
        points: 300,
        order_index: 8,
        explanation: 'Perbandingan berbalik nilai: (6 * 8) / 4 = 48 / 4 = 12 hari.',
      },
    ],
  },
  {
    id: 'logika-asah-otak',
    name: 'Teka-Teki Logika & Asah Otak',
    category: 'Logika & Penalaran',
    description: '8 soal pemikiran kritis, silogisme, dan teka-teki pemecahan masalah.',
    questions: [
      {
        question_text: 'Ada 5 burung di atas pohon. Seorang pemburu menembak 1 burung hingga jatuh. Berapa burung yang tersisa di atas pohon?',
        options: [
          { label: 'A', text: '4 ekor' },
          { label: 'B', text: '0 ekor' },
          { label: 'C', text: '1 ekor' },
          { label: 'D', text: '3 ekor' },
        ],
        correct_answer: 'B',
        points: 100,
        order_index: 1,
        explanation: '0 ekor, karena suara tembakan yang keras membuat burung lainnya terbang kabur.',
      },
      {
        question_text: 'Jika "Semua A adalah B", dan "Beberapa B adalah C", maka kesimpulan yang pasti benar adalah...',
        options: [
          { label: 'A', text: 'Semua A adalah C' },
          { label: 'B', text: 'Beberapa A adalah C' },
          { label: 'C', text: 'Semua C adalah A' },
          { label: 'D', text: 'Belum tentu ada hubungan pasti antara A dan C' },
        ],
        correct_answer: 'D',
        points: 100,
        order_index: 2,
        explanation: 'Dalam logika silogisme, tidak dapat ditarik hubungan pasti antara A dan C tanpa premis tambahan.',
      },
      {
        question_text: 'Ibu Budi mempunyai 4 anak: Timur, Barat, Selatan. Siapakah nama anak keempat?',
        options: [
          { label: 'A', text: 'Utara' },
          { label: 'B', text: 'Tenggara' },
          { label: 'C', text: 'Budi' },
          { label: 'D', text: 'Fajar' },
        ],
        correct_answer: 'C',
        points: 100,
        order_index: 3,
        explanation: 'Ibu BUDI mempunyai 4 anak, jadi anak keempat bernama Budi.',
      },
      {
        question_text: 'Suatu hari seseorang berjalan ke arah selatan sejauh 5 km, lalu belok ke timur 5 km, lalu belok ke utara 5 km. Di manakah posisinya terhadap titik awal?',
        options: [
          { label: 'A', text: 'Tepat di titik awal' },
          { label: 'B', text: '5 km di sebelah timur titik awal' },
          { label: 'C', text: '5 km di sebelah barat titik awal' },
          { label: 'D', text: '10 km di sebelah selatan titik awal' },
        ],
        correct_answer: 'B',
        points: 200,
        order_index: 4,
        explanation: 'Pergerakan selatan 5 km lalu utara 5 km saling meniadakan, menyisakan pergeseran 5 km ke arah timur.',
      },
      {
        question_text: 'Hari ini adalah hari Minggu. Hari apakah 100 hari dari sekarang?',
        options: [
          { label: 'A', text: 'Senin' },
          { label: 'B', text: 'Selasa' },
          { label: 'C', text: 'Rabu' },
          { label: 'D', text: 'Kamis' },
        ],
        correct_answer: 'B',
        points: 200,
        order_index: 5,
        explanation: '100 dibagi 7 = 14 dengan sisa 2 hari. Minggu + 2 hari = hari Selasa.',
      },
      {
        question_text: 'Kata manakah yang tidak termasuk ke dalam kelompok kata berikut: Gitar, Biola, Cello, Seruling?',
        options: [
          { label: 'A', text: 'Gitar' },
          { label: 'B', text: 'Biola' },
          { label: 'C', text: 'Cello' },
          { label: 'D', text: 'Seruling' },
        ],
        correct_answer: 'D',
        points: 200,
        order_index: 6,
        explanation: 'Gitar, biola, dan cello adalah alat musik berdawai, sedangkan seruling adalah alat musik tiup.',
      },
      {
        question_text: 'Di dalam sebuah perlombaan lari, kamu berhasil menyalip pelari di posisi ke-2. Sekarang kamu berada di posisi ke berapa?',
        options: [
          { label: 'A', text: 'Posisi ke-1' },
          { label: 'B', text: 'Posisi ke-2' },
          { label: 'C', text: 'Posisi ke-3' },
          { label: 'D', text: 'Posisi terakhir' },
        ],
        correct_answer: 'B',
        points: 300,
        order_index: 7,
        explanation: 'Menyalip orang di posisi ke-2 berarti kamu mengambil alih posisinya, yaitu posisi ke-2 (bukan ke-1).',
      },
      {
        question_text: 'Berapa banyak angka 9 yang muncul di antara angka 1 sampai 100?',
        options: [
          { label: 'A', text: '10' },
          { label: 'B', text: '19' },
          { label: 'C', text: '20' },
          { label: 'D', text: '21' },
        ],
        correct_answer: 'C',
        points: 300,
        order_index: 8,
        explanation: 'Satuan 9 ada 10 kali (9, 19, 29, ..., 99). Puluhan 9 ada 10 kali (90-99). Angka 99 dihitung 2 kali. Total = 20 kali.',
      },
    ],
  },
];
